// Generated by CoffeeScript 1.7.1
(function() {
  var Evented, cancelAnimationFrame, extend, requestAnimationFrame,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty;

  window.requestAnimationFrame = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;

  window.cancelAnimationFrame = window.cancelAnimationFrame || window.mozCancelAnimationFrame;

  if (typeof requestAnimationFrame === "undefined" || requestAnimationFrame === null) {
    requestAnimationFrame = function(fn) {
      return setTimeout(fn, 50);
    };
    cancelAnimationFrame = function(id) {
      return clearTimeout(id);
    };
  }

  if (!Array.prototype.filter) {
    Array.prototype.filter = function(fn, context) {
      var i, result, value, _i, _ref;
      result = [];
      if (!this || typeof fn !== 'function' || fn instanceof RegExp) {
        throw new TypeError();
      }
      for (i = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (this.hasOwnProperty(i)) {
          value = this[i];
          if (fn.call(context, value, i, this)) {
            result.push(value);
          }
        }
      }
      return result;
    };
  }

  extend = function() {
    var key, out, source, sources, val, _i, _len;
    out = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      source = sources[_i];
      if (source) {
        for (key in source) {
          if (!__hasProp.call(source, key)) continue;
          val = source[key];
          if ((out[key] != null) && typeof out[key] === 'object' && (val != null) && typeof val === 'object') {
            extend(out[key], val);
          } else {
            out[key] = val;
          }
        }
      }
    }
    return out;
  };

  Evented = (function() {
    function Evented() {}

    Evented.prototype.on = function(event, handler, ctx, once) {
      var _base;
      if (once == null) {
        once = false;
      }
      if (this.bindings == null) {
        this.bindings = {};
      }
      if ((_base = this.bindings)[event] == null) {
        _base[event] = [];
      }
      return this.bindings[event].push({
        handler: handler,
        ctx: ctx,
        once: once
      });
    };

    Evented.prototype.once = function(event, handler, ctx) {
      return this.on(event, handler, ctx, true);
    };

    Evented.prototype.off = function(event, handler) {
      var i, _ref, _results;
      if (((_ref = this.bindings) != null ? _ref[event] : void 0) == null) {
        return;
      }
      if (handler == null) {
        return delete this.bindings[event];
      } else {
        i = 0;
        _results = [];
        while (i < this.bindings[event].length) {
          if (this.bindings[event][i].handler === handler) {
            _results.push(this.bindings[event].splice(i, 1));
          } else {
            _results.push(i++);
          }
        }
        return _results;
      }
    };

    Evented.prototype.trigger = function() {
      var args, ctx, event, handler, i, once, _ref, _ref1, _results;
      event = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if ((_ref = this.bindings) != null ? _ref[event] : void 0) {
        i = 0;
        _results = [];
        while (i < this.bindings[event].length) {
          _ref1 = this.bindings[event][i], handler = _ref1.handler, ctx = _ref1.ctx, once = _ref1.once;
          handler.apply(ctx != null ? ctx : this, args);
          if (once) {
            _results.push(this.bindings[event].splice(i, 1));
          } else {
            _results.push(i++);
          }
        }
        return _results;
      }
    };

    return Evented;

  })();

  if (window.Emg == null) {
    window.Emg = {};
  }

  extend(Emg, Evented.prototype);

  Emg.init = function(options) {
    var obj;
    Emg.arr = [];
    Emg.currentNum = 0;
    Emg.targetNum = 0;
    Emg.elems = $('.emg');
    Emg.mediaElems = [];
    Emg.length = Emg.elems.length;
    for (obj in options) {
      Emg[obj] = options[obj];
    }
    if (Emg.divide && Emg.naming) {
      return Emg.bindWindowResize();
    }
  };

  Emg.start = function() {
    Emg.trigger('start');
    Emg.elems.each((function(_this) {
      return function(i, e) {
        return Emg.load($(e));
      };
    })(this));
    Emg.processing = true;
    Emg.processTimer = Date.now();
    return Emg.update();
  };

  Emg.end = function() {
    Emg.trigger('complete');
    return Emg.processing = false;
  };

  Emg.update = function() {
    if (Emg.processing) {
      Emg.processHandler();
      return requestAnimationFrame((function(_this) {
        return function() {
          Emg.trigger('update');
          return Emg.update();
        };
      })(this));
    }
  };

  Emg.processHandler = function() {
    var absDelta, delta, filtered, t;
    t = Date.now();
    if (t - Emg.processTimer >= 100) {
      Emg.processTimer = t;
      filtered = Emg.arr.filter(function(e) {
        return e.state() === 'resolved';
      });
      Emg.targetNum = 0 + filtered.length / Emg.length * 100;
    }
    if (Emg.currentNum >= 100) {
      Emg.end();
      return;
    }
    delta = (Emg.targetNum - Emg.currentNum) / 2;
    absDelta = Math.abs(delta);
    if (absDelta < 0.01) {
      return Emg.currentNum = Emg.targetNum;
    } else {
      return Emg.currentNum += delta;
    }
  };

  Emg.mediaP = function(src) {
    return src.match(/{media}/);
  };

  Emg.getSrc = function(src) {
    Emg.media = Emg.media || Emg.getMedia();
    return src.replace(/{media}/, Emg.media);
  };

  Emg.load = function($e) {
    var alt, d, src, type;
    alt = $e.data('alt');
    src = $e.data('src');
    type = $e.data('type');
    if (Emg.mediaP(src)) {
      Emg.mediaElems.push($e);
      src = Emg.getSrc(src);
    }
    d = $.Deferred(function() {
      var $img;
      $img = $('<img>').attr({
        src: src,
        alt: alt
      });
      $img.on('load', (function(_this) {
        return function(event) {
          return _this.resolve();
        };
      })(this));
      $img.on('error', (function(_this) {
        return function(event) {
          console.log("image doesn't exist");
          return _this.resolve();
        };
      })(this));
      if (type === 'cvs') {
        console.log('load with canvas');
      }
      if (type === 'bg') {
        return $e.css('backgroundImage', 'url(' + src + ')');
      } else {
        return $e.append($img);
      }
    });
    return Emg.add(d);
  };

  Emg.bindWindowResize = function() {
    return $(window).on('resize', function() {
      var t;
      t = Date.now();
      return setTimeout(function() {
        var $e, media, _i, _len, _ref;
        if (t - Emg.resizeTimer < 100) {
          return;
        }
        media = Emg.getMedia();
        if (Emg.media === media) {
          return;
        }
        Emg.media = media;
        _ref = Emg.mediaElems;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          $e = _ref[_i];
          Emg.load($e);
        }
        return Emg.resizeTimer = t;
      }, 200);
    });
  };

  Emg.getMedia = function() {
    var i, num, _i, _ref;
    if (Emg.divide && Emg.naming) {
      i = 0;
      for (num = _i = 0, _ref = Emg.divide.length; 0 <= _ref ? _i < _ref : _i > _ref; num = 0 <= _ref ? ++_i : --_i) {
        if ($(window).width() > Emg.divide[num]) {
          i++;
        }
      }
      return Emg.naming[i];
    } else {
      return console.log('Please provide options "divide" and "naming" for mediaquery to work');
    }
  };

  Emg.add = function(def) {
    return Emg.arr.push(def);
  };

  Emg.init();

  if (typeof define === 'function' && define.amd) {
    define(function() {
      return Emg;
    });
  } else if (typeof exports === 'object') {
    module.exports = Emg;
  } else {
    Emg.start();
  }

}).call(this);

//# sourceMappingURL=easyimage.map
